/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalbases;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
/**
 *
 * @author dimel
 */
public class EmpleadosBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadosBusqueda
     */
    
    private Connection conn;
    
    public EmpleadosBusqueda(Connection con) {
        this.conn = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empleadoBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(168, 187, 191));

        empleadoBusqueda.setBackground(new java.awt.Color(168, 187, 191));
        empleadoBusqueda.setToolTipText("rereqwrw");
        empleadoBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del empleado:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(168, 187, 191));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel3);

        jButton1.setBackground(new java.awt.Color(239, 242, 145));
        jButton1.setText("Nuevo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pulse para buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(empleadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jButton1)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empleadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        busquedaEmpleado(empleadoBusqueda.getText());
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new CrearEmpleado(this.conn).show();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        busquedaEmpleado(empleadoBusqueda.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CrearEmpleado(this.conn).show();
    }//GEN-LAST:event_jButton1ActionPerformed
    
 
    
    private void busquedaEmpleado(String text)
    {   
        try {
            jPanel3.setVisible(true);
            jPanel3.removeAll();
            
            String formatText = "'%" + text + "%'";
            String sql = "SELECT id_empleado, nombre_empleado, apellido_empleado FROM empleado WHERE nombre_empleado LIKE " + formatText;
            Statement statement = this.conn.createStatement();
            ResultSet result = statement.executeQuery(sql);
            
            System.out.println(result);
            
            while ( result.next()){
                crearCajaEmpleado(Integer.toString(result.getInt(1)),result.getString(2), result.getString(3));
            }
            
        } catch (Exception ex) {
            ex.getStackTrace();
        }
    }
    
    private void crearCajaEmpleado(String ced, String nom, String ape){
        System.out.println(ced + " " + nom + " " + ape);
        
        JPanel panel = new JPanel();
        panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0,0,0),1));
        
        Insets ins = new Insets(10,10,10,10);
        
        panel.setBackground(new java.awt.Color(240, 242, 242));
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();

        
        JLabel cedula = new JLabel(ced);
        c.weightx = 0.5;
        c.gridx = 0;
        c.gridy = 0;
        c.insets = ins;
        c.anchor = GridBagConstraints.CENTER;
        cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel.add(cedula, c);
        
        
        
        JLabel nombre = new JLabel(nom);
        c.weightx = 0.1;
        c.gridx = 1;
        c.gridy = 0;
        c.anchor = GridBagConstraints.CENTER;
        panel.add(nombre, c);
        
      
        
        JLabel apellido = new JLabel(ape);
        c.weightx = 0.1;
        c.gridx = 2;
        c.gridy = 0;
        c.anchor = GridBagConstraints.CENTER;
        panel.add(apellido, c);
        
        JButton detalles = new JButton();
        detalles.setText("Detalles");
        detalles.setBackground(new java.awt.Color(55,64,54));
        detalles.setForeground(Color.WHITE);
        c.weightx = 0.1;
        c.gridx = 3;
        c.gridy = 0;
        c.anchor = GridBagConstraints.CENTER;
        panel.add(detalles, c);
        
        // Eventos
        Connection newCon = this.conn;
        
        
        detalles.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArrayList<String> datosEmpleado = getDetallesEmpleado(ced);
        
                for (int i = 0; i < datosEmpleado.size(); i++)
                {
                    System.out.println(datosEmpleado.get(i));
                }
                new DetallesEmpleado(datosEmpleado,newCon).show();
            }
        });
        
        
        jPanel3.add(panel);
        
        jPanel3.updateUI();
       
        
    }
    
    private ArrayList<String> getDetallesEmpleado(String cedula)
    {
        
        ArrayList<String> datosEmpleado = new ArrayList<>();
        try {
            // obteniendo datos del empleado
            String sql = "SELECT concat(nombre_empleado,' ' ,apellido_empleado) as nombre,id_empleado,numero_de_cuenta,cargo_del_empleado,nombre_lugar_de_trabajo,nombre_departamento,concat('$', format(valor_mensual_contrato, 2)) as valor_mensual_contrato,horas_de_trabajo_al_dia,date_format(fecha_inicio_contrato, '%M - %d - %Y') as inicio_contrato,date_format(fecha_final_contrato, '%M - %d - %Y') as final_contrato,pago_seguridad_social,informe_actividades,date_format(fecha_en_la_que_cobra, '%M - %d - %Y') as fecha_en_la_que_cobra, numero_meses_a_cobrar,concat('$', format(valor_total_a_cobrar, 2)) as valor_total_cobro from empleado natural join cargo natural join lugardetrabajo natural join departamento natural join contrato natural join cuentadecobro WHERE id_empleado = " + cedula;
            Statement statement = this.conn.createStatement();
            ResultSet result = statement.executeQuery(sql);
            
            while ( result.next()){
                
                for (int i = 0; i < 15; i++)
                {
                    datosEmpleado.add(result.getString(i+1));
                }
  
            }
            
            return datosEmpleado;
        } catch (SQLException ex) {
            Logger.getLogger(EmpleadosBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return datosEmpleado;
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empleadoBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
